{
 "title": "NET6 Runtime",
 "tags": [ "fuyuan" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(process_runtime_dotnet_threadpool_thread_count{}, namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(process_runtime_dotnet_threadpool_thread_count{namespace=\"$namespace\"}, job)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(process_runtime_dotnet_threadpool_thread_count{namespace=\"$namespace\",job=~\"$job\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resource", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg by (pod) (irate(process_cpu_time_s{pod=~\"$pod\"}[1m])) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_memory_usage_By{pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "GC Gen0",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(process_runtime_dotnet_gen_0_gc_count{namespace=\"$namespace\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Gen1",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "rate(process_runtime_dotnet_gen_1_gc_count{namespace=\"$namespace\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Gen2",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "rate(process_runtime_dotnet_gen_2_gc_count{namespace=\"$namespace\", pod=~\"$pod\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Heap",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_heap_By{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC Committed",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_committed_Mi{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Threading", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "ThreadPool Size",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_threadpool_thread_count{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ThreadPool Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "process_runtime_dotnet_threadpool_queue_length{namespace=\"$namespace\", pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ThreadPool Completed Items Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(process_runtime_dotnet_threadpool_completed_items_count{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Lock Contention",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "rate(process_runtime_dotnet_monitor_lock_contention_count{namespace=\"$namespace\", pod=~\"$pod\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}