{
 "title": "Service RED",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total, service_name)"
    }
   },
   {
    "name": "operation",
    "query": {
     "query": "label_values(traces_spanmetrics_calls_total{service_name=\"$service\"},operation)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Operations",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_latency_count{service_name=\"$service\",operation=~\"$operation\"}[5m])) by (operation)"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(traces_spanmetrics_latency_bucket{service_name=\"$service\",operation=~\"$operation\"}[5m])) by (operation, le))"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(traces_spanmetrics_latency_bucket{service_name=\"$service\",operation=~\"$operation\"}[5m])) by (operation, le))"
    },
    {
     "expr": "sum(rate(traces_spanmetrics_latency_count{service_name=\"$service\",operation=~\"$operation\",status_code=\"STATUS_CODE_ERROR\"}[5m])) by (operation)\r\n/\r\nsum(rate(traces_spanmetrics_latency_count{service_name=\"$service\",operation=~\"$operation\"}[5m])) by (operation)"
    }
   ]
  },
  {
   "title": "Histogram",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(traces_spanmetrics_latency_bucket{service_name=\"$service\",operation=~\"$operation\",le!=\"9.223372036854775e+12\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Persentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(traces_spanmetrics_latency_bucket{service_name=\"$service\",operation=~\"$operation\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(traces_spanmetrics_latency_bucket{service_name=\"$service\",operation=~\"$operation\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(traces_spanmetrics_latency_bucket{service_name=\"$service\",operation=~\"$operation\"}[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_latency_count{service_name=\"$service\",operation=~\"$operation\"}[1m])) by (operation) > 0",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Status Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(traces_spanmetrics_latency_count{service_name=\"$service\",operation=~\"$operation\"}[$__range])) by (operation, status_code) > 0",
     "legendFormat": "{{operation}} {{status_code}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(traces_spanmetrics_latency_count{service_name=\"$service\",operation=~\"$operation\",status_code=\"STATUS_CODE_ERROR\"}[5m])) by (operation) > 0",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}